#pragma once

const unsigned int BACKSIZEX = 1280;
const unsigned int BACKSIZEY = 768;

enum SCENETYPE {SCENE_STATIC, SCENE_LOGO, SCENE_STAGE, SCENE_BOSS, SCENE_END};

enum SUBJECTMESSAGE //By.PSH 
{
	MESSAGE_CURRENT_PLAYER_DATA,
	MESSAGE_PLAYER_DATA,
	MESSAGE_CAMERA_DATA,
};